### PR TITLE
Use ResourceLoader for MW 1.24+

### LINKED ISSUE #4: no media links
Hi, I just installed this extension. The blocks weren't being rendered with any styling, so I looked in the source and could see that the relative links to the `extensions/MasonryMainPage/Masonry.css` stylesheet wasn't being loaded. This is with MW 1.24.2.

Any pointers where I might look for what's wrong?

### PR DESCRIPTION
**Pull request by jamesmontalvo3**
Pulling in changes from @JosefAssad.

Closes #4

### CODE REVIEW

**Comment by JosefAssad** [comment]
Apologies for the radio silence, have been a bit overloaded. Thank you for the merge. :)

**Comment by jamesmontalvo3** [comment]
Had to remove the minified JS and CSS files. I've seen them have issues with ResourceLoader in the past.

**Comment by jamesmontalvo3** [comment]
Had to add `'position' => 'top'` to `$wgResourceModules` to make JS and CSS files load earlier. This is not required for MasonryMainPage, but unfortunately is required for other things which use MasonryMainPage. In the future this should be fixed such that MasonryMainPage modules only need to be loaded on MasonryMainPage pages. See enterprisemediawiki/Meza1#149 for more info.

**Comment by jamesmontalvo3** [comment]
@JosefAssad no prob for the silence. Thanks for the patch!

**Comment by jamesmontalvo3** [comment]
This change has been tested on Meza1 platform (MW 1.25) as well as the current EVA Wiki platform (MW 1.23). I believe it's ready to merge.

**Comment by darenwelsh** [comment]
Awesome! Thanks to both of you!

**Pull request merged**
